-- MySQL Script generated by MySQL Workbench
-- Wed 15 Feb 2017 10:20:54 PM BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema cadvision
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cadvision
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cadvision` DEFAULT CHARACTER SET latin1 ;
USE `cadvision` ;

-- -----------------------------------------------------
-- Table `cadvision`.`contato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cadvision`.`contato` (
  `id_contato` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `contato_nome` VARCHAR(50) NULL DEFAULT NULL,
  `contato_email` VARCHAR(50) NULL DEFAULT NULL,
  `contato_assunto` VARCHAR(11) NULL DEFAULT NULL,
  `contato_mensagem` TEXT NULL DEFAULT NULL,
  `contato_data` DATE NULL DEFAULT NULL,
  `contato_hora` TIME NULL DEFAULT NULL,
  `contato_ip` VARCHAR(45) NULL DEFAULT NULL,
  `status` INT(1) NOT NULL,
  PRIMARY KEY (`id_contato`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cadvision`.`pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cadvision`.`pessoa` (
  `id_pessoa` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(150) NOT NULL,
  `rg` VARCHAR(14) NULL DEFAULT NULL,
  `sexo` CHAR(1) NULL DEFAULT NULL,
  `cpf` VARCHAR(11) NULL DEFAULT NULL,
  `cidade` VARCHAR(50) NULL DEFAULT NULL,
  `uf` CHAR(2) NULL DEFAULT NULL,
  `telefone` VARCHAR(15) NULL DEFAULT NULL,
  `endereco` VARCHAR(100) NULL DEFAULT NULL,
  `cep` VARCHAR(10) NULL DEFAULT NULL,
  `bairro` VARCHAR(30) NULL DEFAULT NULL,
  `numero` VARCHAR(6) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `obs` TEXT NOT NULL,
  `foto` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_pessoa`))
ENGINE = InnoDB
AUTO_INCREMENT = 24
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cadvision`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cadvision`.`usuario` (
  `id_usuario` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `login` VARCHAR(20) NOT NULL,
  `senha` VARCHAR(50) NOT NULL,
  `email` VARCHAR(50) NULL DEFAULT NULL,
  `data` DATE NULL DEFAULT NULL,
  `hora` TIME NULL DEFAULT NULL,
  `ip` VARCHAR(20) NULL DEFAULT NULL,
  `status` INT(1) NULL DEFAULT NULL,
  `nivel` INT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cadvision`.`visita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cadvision`.`visita` (
  `id_visita` INT(11) NOT NULL AUTO_INCREMENT,
  `visitante_data` DATE NULL DEFAULT NULL,
  `visitante_hora` TIME NULL DEFAULT NULL,
  `visita_saida` TIME NULL,
  `visitante_quem_vis` VARCHAR(50) NULL DEFAULT NULL,
  `visitante_obs` TEXT NULL DEFAULT NULL,
  `id_pessoa` INT(11) NOT NULL,
  `status` INT(1) NOT NULL,
  `cracha` VARCHAR(45) NULL,
  PRIMARY KEY (`id_visita`, `id_pessoa`),
  INDEX `fk_visita_pessoa1_idx` (`id_pessoa` ASC),
  CONSTRAINT `visita_ibfk_1`
    FOREIGN KEY (`id_pessoa`)
    REFERENCES `cadvision`.`pessoa` (`id_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cadvision`.`visitado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cadvision`.`visitado` (
  `id_visitado` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `visitado_nome` VARCHAR(100) NOT NULL,
  `visitado_secao` VARCHAR(45) NULL DEFAULT NULL,
  `status` INT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id_visitado`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cadvision`.`acesso_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cadvision`.`acesso_usuario` (
  `id_acesso` INT NOT NULL AUTO_INCREMENT,
  `login_acesso` VARCHAR(60) NULL,
  `ip_acesso` VARCHAR(45) NULL,
  `data_acesso` VARCHAR(45) NULL,
  `obs_acesso` VARCHAR(45) NULL,
  PRIMARY KEY (`id_acesso`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

